# Generated by Django 5.2.3 on 2025-07-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('distance_to_work', models.FloatField(help_text='Distance to work in miles')),
                ('distance_to_school', models.FloatField(help_text='Distance to school in miles')),
                ('distance_to_other', models.FloatField(help_text='Distance to other location in miles')),
                ('bedrooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
